name: Languages Card

on:
  schedule:
    - cron: "0 7 * * 1"   # weekly, 07:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bentoBAUX
          # output
          filename: metrics-languages.svg
          template: classic
          base: header
          config_timezone: Europe/Berlin
          # languages plugin
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, bytes-size
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          # filters
          repositories_affiliations: owner   # ignore orgs you don't own
          repositories_forks: no             # ignore forks
